# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b9691ec67020b7e77d174a65a5cf17c4c2daf941fe5650e537eea33ad77ef206ed110f468f8c41757ead9b3823ab257cb10e4d172619dca19859ff954c7664b

test:
  secret_key_base: 5509b12d1626148594169f7a62d9cbc828634cc32ad97b468536741098eece2a48b17b23b6d45945c0213a2a6cabc5d47791d1d4a0fbe8446439115bec693cc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
